name: LeetCode Monitor

on:
  schedule:
    - cron: "* * * * *" # Runs every hour
  workflow_dispatch: # Optional: allows manual trigger

jobs:
  run-leetcode-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LeetCode monitor
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python main.py
